library(srppp)
library(DiagrammeR)
library(uwot)
library(mclust)
library(pheatmap)

# download current SRPPP register
current_register <- srppp_dm()
dm_draw(current_register)

# comments (in German)
S = current_register$CodeS$CodeS_de |> unique()
R = current_register$CodeR$CodeR_de |> unique()
current_register$application_comments$application_comment_de |> unique()
current_register$obligations$code |> unique()

# extract obligations
x = current_register$obligations$obligation_de |>
  table() |>
  sort(decreasing = T)
y = names(x)
write.csv(data.frame(id = 1:length(y), obligation = y), "obligations.csv", row.names = FALSE)


# current_register$products
# current_register$ingredients
# current_register$formulation_codes
# current_register$substances

# current_register$uses |> View()
# current_register$uses$units_de |> unique()
# current_register$cultures$culture_de |> unique()
# current_register$culture_forms



# Code S to RDF
# X = as.data.frame(unique(current_register$CodeS[,3:6]))
# for (i in 1:nrow(X)) {
#   cat(sprintf("\n:hazardLabelS%s a :hazardLabel ; \n\trdfs:label \"%s\"@de , \n\t\t\"%s\"@fr , \n\t\t\"%s\"@it", i, X[i,2], X[i,3], X[i,4]))
#   if(is.na(X[i,1]) | grepl("^\\s*$", X[i,1])) cat(".") else cat(sprintf(" ;\n\t:hasGHScode \"%s\" .", X[i,1]))
# }

# load embeddings generated by OpenAI
data = read.csv("SRPPP/embeddings.csv")
X = as.matrix(data[,-c(1:2)])

# PCA
PCA = prcomp(X)
plot(100*cumsum(PCA$sdev^2)/sum(PCA$sdev^2), log = "x", type = "l", lwd = 4, xlab = "Number of components", ylab = "Variance explained [%]", las = 1)
abline(h = seq(0,100,10), v = c(1,5,10,50,100,500,1000), lty = 3)

# UMAP
UMAP = umap(X, n_neighbors = 50, n_components = 2, metric = "euclidean", verbose = TRUE)
plot(UMAP, pch = 16, cex = 0.5)

# hierarchical clustering
HC = hclust(dist(PCA$x[,1:10]))
plot(HC, labels = FALSE, hang = 0)
k = 11
plot(UMAP, pch = 16, col = viridis::viridis(k)[cutree(HC, k = k)])
# heatmap(as.matrix(dist(X[,1:10])))

GMM = Mclust(PCA$x[,1:30], modelNames = "VVV", G = 1:k)
#GMM = Mclust(UMAP, modelNames = "VVV", G = 1:k)
plot(GMM, what = "BIC")
plot(GMM, what = "uncertainty", dimens = 1:3, col = viridis::viridis(k))
plot(PCA$x[,1:2], pch = 16, col = viridis::viridis(GMM$G)[GMM$classification])
GMM$parameters$mean
GMM$G

# export results
write.csv(data.frame(
  PC1 = PCA$x[,1],
  PC2 = PCA$x[,2],
  UMAP1 = UMAP[,1],
  UMAP2 = UMAP[,2],
  HC = LETTERS[cutree(HC, k = k)],
  GMM = LETTERS[GMM$classification],
  uncertainty = GMM$uncertainty,
  obligation = data$obligation,
  id = data$id), "SRPPP/results.csv", row.names = FALSE)


results[results$GMM=="B","obligation"]
